baseURL = 'https://www.charleshbaker.com/'
languageCode = 'en-us'
title = "Charles's Portfolio"
theme = "basic"

[params]
  author = "Charles H. Baker"
  description = "Charles' portfolio site"
  googleAnalytics = "G-ZB8VBK5JR6"

  gh_url = "https://api.github.com/users"
  gh_user = "charleshbaker"
